version: '2'
services:
  web:
    build: .
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html
    ports:
      - "80:80"
  verbecc_svc:
    image: "bretttolbert/verbecc-svc:latest"
    ports:
      - "8000:8000"
    expose:
      - "8000"
