version: '3'
services:
  web:
    build: .
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html
    ports:
      - "80:80"
  verb_conjugate_fr:
    image: "verb_conjugate_fr:latest"
    ports:
      - "8000:8000"
    expose:
      - "8000"
