version: '3.9'
services:

  verbecc-svc:
    image: "bretttolbert/verbecc-svc:latest"
    container_name: verbecc-svc
    environment:
      - foo=bar
    expose:
      - "8000"

  verbecc-ui:
    build: ./verbecc-ui
    container_name: verbecc-ui
    depends_on:
      - verbecc-svc
    ports:
      - "80:80"
