version: '3'
services:

  verbecc-svc:
    image: "bretttolbert/verbecc-svc:latest"
    container_name: verbecc-svc
    environment:
      - foo=bar
    ports:
      - 8000:8000

  verbecc-ui:
    build: ./verbecc-ui
    container_name: verbecc-ui
    ports:
      - 80:80
    links:
      - verbecc-svc
